access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:11018/sstest
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: none
    open-in-view: true
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:11018/
    password: password
    user: root
    schemas: sstest
    locations: classpath:db/migration
