access-token:
  private: "access-refresh-token-keys/access-token-private.key"
  public: "access-refresh-token-keys/access-token-public.key"
refresh-token:
  private: "access-refresh-token-keys/refresh-token-private.key"
  public: "access-refresh-token-keys/refresh-token-public.key"
server:
  error:
    include-binding-errors: always
    include-message: always